name: Integration (Scale down)

on:
  pull_request:
    types:
      - closed

jobs:
  environment:
    name: Environment
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'release/')

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: 'SAKPaaS/deployment'

      - name: Scale down (frontend)
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: scale --replicas=0 -f frontend/integration/deployment.yaml || true
