name: Linter

# Trigger on push
on: push

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare
        run: cd SAKPaaS && npm ci

      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'
