name: Tests

# Trigger on push
on: push

jobs:
  tests:
    name: Run Tests
    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      working-directory: ./SAKPaaS
      run: npm ci
    - name: Install Puppeteer
      working-directory: ./SAKPaaS
      run: npm install puppeteer --save-dev
    - name: Test
      working-directory: ./SAKPaaS
      run: npm test
